"""Regenerate the branch summary in `docs/CODEBASE.md` from git itself.

The summary had already drifted once, and silently: it named `feat/prompt-search` as the
tip long after sixteen further commits had landed, so anyone following the checkout
instruction - a supervisor, an examiner, a future reader - would have got a copy missing the
entire front end, the database and both searches, with nothing to indicate anything was
absent. Hand-maintained counts in a document that changes every session cannot stay true.

So the numbers come from git. This rewrites the block between the two markers in
`docs/CODEBASE.md` and leaves the rest of the file alone.

    uv run python scripts/branch_report.py           # show what it would write
    uv run python scripts/branch_report.py --write   # rewrite the block
    uv run python scripts/branch_report.py --check    # exit 1 if the block is stale
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "CODEBASE.md"
START = "<!-- branch-report:start -->"
END = "<!-- branch-report:end -->"


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def branches() -> list[str]:
    return git("for-each-ref", "--format=%(refname:short)", "refs/heads/").splitlines()


def tip_branch() -> str:
    """The branch that contains every other branch on the main chain.

    `pilot/model-selection` is excluded by construction rather than by name: it branches
    from the first commit and is not an ancestor of anything, so it contains no other
    branch and can never be the chain's tip.
    """
    best, best_count = "", -1
    for branch in branches():
        contained = [
            b for b in git("branch", "--merged", branch).replace("*", "").split()
            if b != branch
        ]
        if len(contained) > best_count:
            best, best_count = branch, len(contained)
    return best


def counts(ref: str) -> dict[str, int]:
    def n(*pattern: str) -> int:
        out = git("ls-tree", "-r", "--name-only", ref)
        return sum(
            1 for line in out.splitlines()
            if line.endswith(".py") and any(line.startswith(p) for p in pattern)
        )

    return {
        "commits": int(git("rev-list", "--count", ref)),
        "branches": len(branches()),
        "src": n("src/"),
        "experiments": n("experiments/"),
        "tests": n("tests/"),
    }


def block() -> str:
    tip = tip_branch()
    c = counts(tip)
    others = len(branches()) - 3  # main, the tip, and the pilot are named separately
    return f"""{START}
`main` holds **only the planning documents**. Every line of code sits on a chain of feature
branches, each built on the one before, with the newest work at the tip.

```
main                     PLAN.md · SUPER_PLAN.md · TODO.md · README.md · 2 .docx · .gitignore · requirements.txt
  └── setup/project-scaffold
        └── feat/dataset-manifest
              └── ... {others} more branches, each stacked on the last ...
                    └── {tip}      <- the tip: everything is here
```

**The tip branch (`{tip}`) contains the whole project** — {c['commits']} commits,
{c['src']} source modules, {c['experiments']} experiment scripts, {c['tests']} test files.

To get the working code:

```bash
git checkout {tip}
```

Because the branches are stacked rather than parallel, they cannot be merged independently —
each contains all its ancestors. To bring everything into `main` at once:

```bash
git checkout main && git merge {tip}
```

To review the work in stages instead, open pull requests in branch order; each diff will show
only its own commits.

> This block is generated by `scripts/branch_report.py` from git. It named a tip that was
> sixteen commits stale once; regenerate it rather than editing the numbers by hand.
{END}"""


def rewrite(text: str) -> str:
    before, _, rest = text.partition(START)
    _, _, after = rest.partition(END)
    if not rest or not after and END not in rest:
        raise SystemExit(f"markers {START} / {END} not found in {DOC.name}")
    return before + block() + after


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="rewrite the block in place")
    ap.add_argument("--check", action="store_true", help="exit 1 if the block is stale")
    args = ap.parse_args()

    current = DOC.read_text(encoding="utf-8")
    updated = rewrite(current)
    if args.write:
        DOC.write_text(updated, encoding="utf-8")
        print(f"rewrote the branch block in {DOC.relative_to(ROOT)}")
    elif args.check:
        if updated != current:
            print("the branch block in docs/CODEBASE.md is stale; run with --write")
            sys.exit(1)
        print("branch block is current")
    else:
        print(block())


if __name__ == "__main__":
    main()
